#!/usr/bin/env sh
echo Launching Veracode CLI....
if [ -z "$CI_COMMIT_BRANCH" ]
then
      python /veracode/veracode.py -b master "$@"
else
      python /veracode/veracode.py -b $CI_COMMIT_BRANCH "$@"
fi

